
language: objective-c
osx_image: xcode9.4
xcode_workspace: in-ios.xcodeproj
xcode_scheme: Test
xcode_sdk: iphonesimulator11.4

branches:
    only:
        - dev
        - master
env:
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

script:
  - set -o pipefail
  - xcodebuild clean test -workspace in-ios.xcworkspace -scheme in-ios_1 -destination 'platform=iOS Simulator,name=iPhone 7' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  - swiftlint