language: objective-c
osx_image: xcode9.4.1

branches:
  only:
    - dev
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.3.3
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
  - xcodebuild -workspace in-ios.xcworkspace -scheme in-ios -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c