language: objective-c
osx_image: xcode10
xcode_workspace: in-ios.xcworkspace
xcode_scheme: in-ios_test
xcode_sdk: iphonesimulator12.0

branches:
    only:
        - master
env:
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

install:
  - true

before_script:
  - git lfs pull

script:
  - set -o pipefail
  - xcodebuild -workspace in-ios.xcworkspace -scheme in-ios_test -destination 'platform=iOS Simulator,name=iPhone 7' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty -c
